name: BabyPotion
version: '${version}'
main: me.zepsizola.babypotion.BabyPotion
api-version: '1.20'
author: Zepsi_Zola_
description: A plugin that turns any mob to their baby counterpart when babypotions are splashed on them.
depend: [GriefPrevention]
commands:
  babypotion:
    description: Gives the user a babypotion.
    usage: /babypotion
    aliases: [bp]
permissions:
  babypotion.babypotion:
    description: Allows using the /babypotion command
    default: op